// <auto-generated />
using System;
using ApiBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215195757_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiBackend.Models.Puesto", b =>
                {
                    b.Property<int>("PuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PuestoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UbicacionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PuestoId");

                    b.ToTable("Puestos");

                    b.HasData(
                        new
                        {
                            PuestoId = 1,
                            Activo = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Tunshuruco",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ApiBackend.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            Nombre = "CECOM"
                        },
                        new
                        {
                            RolId = 3,
                            Nombre = "CordinadorOperativo"
                        },
                        new
                        {
                            RolId = 4,
                            Nombre = "SupervisorArea"
                        });
                });

            modelBuilder.Entity("ApiBackend.Models.Ronda", b =>
                {
                    b.Property<int>("RondaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RondaId"));

                    b.Property<int>("CoordinadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRevision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RondaId");

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Rondas");
                });

            modelBuilder.Entity("ApiBackend.Models.RondaEstado", b =>
                {
                    b.Property<int>("RondaEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RondaEstadoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("RondaEstadoId");

                    b.ToTable("RondaEstados");

                    b.HasData(
                        new
                        {
                            RondaEstadoId = 1,
                            Activo = false,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            RondaEstadoId = 2,
                            Activo = false,
                            Nombre = "En proceso"
                        },
                        new
                        {
                            RondaEstadoId = 3,
                            Activo = false,
                            Nombre = "Finalizada"
                        },
                        new
                        {
                            RondaEstadoId = 4,
                            Activo = false,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("ApiBackend.Models.RondaPuesto", b =>
                {
                    b.Property<int>("RondaPuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RondaPuestoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PuestoId")
                        .HasColumnType("integer");

                    b.Property<int>("RondaId")
                        .HasColumnType("integer");

                    b.Property<int>("RondaPuestoEstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RondaPuestoId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("RondaId");

                    b.HasIndex("RondaPuestoEstadoId");

                    b.ToTable("RondaPuestos");
                });

            modelBuilder.Entity("ApiBackend.Models.RondaPuestoEstado", b =>
                {
                    b.Property<int>("RondaPuestoEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RondaPuestoEstadoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("RondaPuestoEstadoId");

                    b.ToTable("RondaPuestoEstados");

                    b.HasData(
                        new
                        {
                            RondaPuestoEstadoId = 1,
                            Activo = false,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            RondaPuestoEstadoId = 2,
                            Activo = false,
                            Nombre = "En supervisión"
                        },
                        new
                        {
                            RondaPuestoEstadoId = 3,
                            Activo = false,
                            Nombre = "Con observaciones"
                        },
                        new
                        {
                            RondaPuestoEstadoId = 4,
                            Activo = false,
                            Nombre = "Completado"
                        },
                        new
                        {
                            RondaPuestoEstadoId = 5,
                            Activo = false,
                            Nombre = "No visitado"
                        });
                });

            modelBuilder.Entity("ApiBackend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("UserId");

                    b.HasIndex("RolId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "",
                            PasswordHash = "71245503",
                            RolId = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "71245503"
                        });
                });

            modelBuilder.Entity("ApiBackend.Models.Ronda", b =>
                {
                    b.HasOne("ApiBackend.Models.User", "Coordinador")
                        .WithMany("RondasCoordinadores")
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiBackend.Models.RondaEstado", "RondaEstado")
                        .WithMany("Rondas")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiBackend.Models.User", "Supervisor")
                        .WithMany("RondasSupervisores")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordinador");

                    b.Navigation("RondaEstado");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ApiBackend.Models.RondaPuesto", b =>
                {
                    b.HasOne("ApiBackend.Models.Puesto", "Puesto")
                        .WithMany("RondaPuestos")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiBackend.Models.Ronda", "Ronda")
                        .WithMany("RondaPuestos")
                        .HasForeignKey("RondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiBackend.Models.RondaPuestoEstado", "RondaPuestoEstado")
                        .WithMany("RondaPuestos")
                        .HasForeignKey("RondaPuestoEstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Puesto");

                    b.Navigation("Ronda");

                    b.Navigation("RondaPuestoEstado");
                });

            modelBuilder.Entity("ApiBackend.Models.User", b =>
                {
                    b.HasOne("ApiBackend.Models.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ApiBackend.Models.Puesto", b =>
                {
                    b.Navigation("RondaPuestos");
                });

            modelBuilder.Entity("ApiBackend.Models.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApiBackend.Models.Ronda", b =>
                {
                    b.Navigation("RondaPuestos");
                });

            modelBuilder.Entity("ApiBackend.Models.RondaEstado", b =>
                {
                    b.Navigation("Rondas");
                });

            modelBuilder.Entity("ApiBackend.Models.RondaPuestoEstado", b =>
                {
                    b.Navigation("RondaPuestos");
                });

            modelBuilder.Entity("ApiBackend.Models.User", b =>
                {
                    b.Navigation("RondasCoordinadores");

                    b.Navigation("RondasSupervisores");
                });
#pragma warning restore 612, 618
        }
    }
}
